import { Banner, MediaCard } from "@components";
import { MEDIA } from "@constants";
import { MediaProps } from "@definitions";
import { getTrendingMovie, getTrendingTv } from "@utils/tmdb/trending";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | TMDB",
  description: "Generated by create next app",
};

export default async function Home() {
  const trendingMovies = (await getTrendingMovie({}))?.data?.results || [];
  const trendingTv = (await getTrendingTv({}))?.data?.results || [];
  const results: MediaProps[] = [...trendingMovies, ...trendingTv];
  console.log(results);

  return (
    <>
      <Banner media={results[0]} mediaType={MEDIA.MOVIE} />
      <MediaCard media={results[0]} />
    </>
  );
}
