import { Banner } from "@common";
import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: "Home | TMDB",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function Home() {
  return <Banner />;
}
